#pragma once
#include "runtime_package.hpp"
#include <map>
namespace forge {
struct GameExportRequest {
    std::filesystem::path destination, runtime_kit, inspection_runtime;
    // Explicit deployment inventories generated by the matching SDK build helper.
    std::map<std::string, std::filesystem::path> module_kits;
    nlohmann::json reference_schema;
};
struct GameExportProgress {
    std::string stage;
    unsigned completed = 0, total = 6;
};
using GameExportObserver = std::function<void(const GameExportProgress&)>;
// Same service for CLI/editor. Caller retains the project lease and suspends
// other publishers. UI discovery publication is a separate authoring operation.
nlohmann::json export_standalone_game(const ProjectLease&, const GameExportRequest&,
                                      const RuntimeUiInspector& = {}, GameExportObserver = {},
                                      std::stop_token = {});
// Recover an interrupted promotion before reusing the output. Never adopts an
// unrelated directory. A completed promotion remains committed on recovery.
void recover_game_export(const std::filesystem::path& destination);
} // namespace forge
