# Reuse the editor's exact upstream targets when present. Standalone headless
# tools compose native loader subdirectories without Dear ImGui or NativeApp.
if(NOT TARGET Diligent-AssetLoader)
 foreach(feature DIRECT3D11 DIRECT3D12 OPENGL VULKAN METAL WEBGPU ARCHIVER SUPER_RESOLUTION)
  set(DILIGENT_NO_${feature} ON CACHE BOOL "Headless native asset tooling" FORCE)
 endforeach()
 # Native Core CMake requires a configured backend even for CPU loader code.
 # Its static archives can be linked without creating a device or loading a driver.
 if(WIN32)
  set(DILIGENT_NO_DIRECT3D12 OFF CACHE BOOL "Required native Core backend" FORCE)
 else()
  set(DILIGENT_NO_VULKAN OFF CACHE BOOL "Required native Core backend" FORCE)
 endif()
 set(DILIGENT_BUILD_TOOLS OFF CACHE BOOL "Compose CPU loader targets explicitly" FORCE)
 set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
 set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
 set(DILIGENT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
 set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
 set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
 set(DILIGENT_NO_GLSLANG ON CACHE BOOL "Model admission profile has no shader compiler" FORCE)
 set(DILIGENT_NO_HLSL ON CACHE BOOL "Model admission profile has no shader compiler" FORCE)
 set(DILIGENT_ENABLE_DRACO OFF CACHE BOOL "Enable only with codec admission integration" FORCE)
 set(DILIGENT_USE_RAPIDJSON OFF CACHE BOOL "Retain selected native loader JSON implementation" FORCE)
 include(cmake/diligent_source.cmake)
 FetchContent_MakeAvailable(diligent)
 set(DILIGENT_TOOLS_DIR "DiligentTools")
 foreach(part ThirdParty TextureLoader AssetLoader)
  add_subdirectory("${diligent_SOURCE_DIR}/DiligentTools/${part}"
   "${diligent_BINARY_DIR}/DiligentTools/${part}" EXCLUDE_FROM_ALL)
 endforeach()
endif()
add_library(forge_texture_import STATIC src/texture_diligent.cpp src/texture_import.cpp src/texture_png.c src/texture_jpeg.c)
target_include_directories(forge_texture_import PRIVATE "${diligent_SOURCE_DIR}/DiligentTools/ThirdParty/stb")
target_link_libraries(forge_texture_import PUBLIC forge_texture PRIVATE PNG::PNG Diligent-TextureLoader Diligent-GraphicsAccessories Diligent-BuildSettings)
if(WIN32)
 target_compile_definitions(forge_texture_import PRIVATE NOMINMAX)
endif()
add_library(forge_gltf_native STATIC src/gltf_native.cpp src/gltf_mesh.cpp src/gltf_hierarchy.cpp src/gltf_skin.cpp src/gltf_animation.cpp src/gltf_cook_mesh.cpp)
target_include_directories(forge_gltf_native PRIVATE
 "${diligent_SOURCE_DIR}/DiligentTools/ThirdParty/tinygltf")
target_link_libraries(forge_gltf_native PUBLIC forge_assets forge_mesh PRIVATE Diligent-AssetLoader Diligent-GraphicsAccessories Diligent-BuildSettings)
if(WIN32)
 target_compile_definitions(forge_gltf_native PRIVATE NOMINMAX)
endif()
if(BUILD_TESTING)
 add_executable(forge_texture_import_tests tests/texture_import_tests.cpp)
 target_include_directories(forge_texture_import_tests PRIVATE src)
 target_link_libraries(forge_texture_import_tests PRIVATE forge_texture_import PNG::PNG Diligent-TextureLoader Diligent-Common Diligent-BuildSettings)
 add_test(NAME texture_import COMMAND forge_texture_import_tests)
 set_tests_properties(texture_import PROPERTIES TIMEOUT 60)
 add_executable(forge_gltf_official_tests tests/gltf_official_tests.cpp)
 target_include_directories(forge_gltf_official_tests PRIVATE src)
 target_link_libraries(forge_gltf_official_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_official_negative_scale COMMAND forge_gltf_official_tests "${CMAKE_CURRENT_SOURCE_DIR}/samples/gltf/NegativeScaleTest")
 set_tests_properties(gltf_official_negative_scale PROPERTIES TIMEOUT 45)
 add_executable(forge_gltf_animation_tests tests/gltf_animation_tests.cpp)
 target_include_directories(forge_gltf_animation_tests PRIVATE src)
 target_link_libraries(forge_gltf_animation_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_animation_admission COMMAND forge_gltf_animation_tests)
 set_tests_properties(gltf_animation_admission PROPERTIES TIMEOUT 45)
 add_executable(forge_gltf_hierarchy_tests tests/gltf_hierarchy_tests.cpp)
 target_include_directories(forge_gltf_hierarchy_tests PRIVATE src)
 target_link_libraries(forge_gltf_hierarchy_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_hierarchy COMMAND forge_gltf_hierarchy_tests)
 set_tests_properties(gltf_hierarchy PROPERTIES TIMEOUT 45)
 add_executable(forge_gltf_mesh_tests tests/gltf_mesh_tests.cpp)
 target_include_directories(forge_gltf_mesh_tests PRIVATE src)
 target_link_libraries(forge_gltf_mesh_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_mesh_processing COMMAND forge_gltf_mesh_tests)
 set_tests_properties(gltf_mesh_processing PROPERTIES TIMEOUT 45)
 add_executable(forge_gltf_native_tests tests/gltf_native_tests.cpp)
 target_include_directories(forge_gltf_native_tests PRIVATE src
  "${diligent_SOURCE_DIR}/DiligentTools/ThirdParty/tinygltf")
 target_link_libraries(forge_gltf_native_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_native_capture COMMAND forge_gltf_native_tests "${CMAKE_BINARY_DIR}/gltf-native-tests")
 set_tests_properties(gltf_native_capture PROPERTIES TIMEOUT 45)
endif()
