# Reuse the editor's exact upstream targets when present. Standalone headless
# tools compose native loader subdirectories without Dear ImGui or NativeApp.
if(NOT TARGET Diligent-AssetLoader)
 foreach(feature DIRECT3D11 DIRECT3D12 OPENGL VULKAN METAL WEBGPU ARCHIVER SUPER_RESOLUTION)
  set(DILIGENT_NO_${feature} ON CACHE BOOL "Headless native asset tooling" FORCE)
 endforeach()
 # Native Core CMake requires a configured backend even for CPU loader code.
 # Its static archives can be linked without creating a device or loading a driver.
 if(WIN32)
  set(DILIGENT_NO_DIRECT3D12 OFF CACHE BOOL "Required native Core backend" FORCE)
 else()
  set(DILIGENT_NO_VULKAN OFF CACHE BOOL "Required native Core backend" FORCE)
 endif()
 set(DILIGENT_BUILD_TOOLS OFF CACHE BOOL "Compose CPU loader targets explicitly" FORCE)
 set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
 set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
 set(DILIGENT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
 set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
 set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
 set(DILIGENT_NO_GLSLANG ON CACHE BOOL "Model admission profile has no shader compiler" FORCE)
 set(DILIGENT_NO_HLSL ON CACHE BOOL "Model admission profile has no shader compiler" FORCE)
 set(DILIGENT_ENABLE_DRACO OFF CACHE BOOL "Enable only with codec admission integration" FORCE)
 set(DILIGENT_USE_RAPIDJSON OFF CACHE BOOL "Retain selected native loader JSON implementation" FORCE)
 include(cmake/diligent_source.cmake)
 FetchContent_MakeAvailable(diligent)
 set(DILIGENT_TOOLS_DIR "DiligentTools")
 foreach(part ThirdParty TextureLoader AssetLoader)
  add_subdirectory("${diligent_SOURCE_DIR}/DiligentTools/${part}"
   "${diligent_BINARY_DIR}/DiligentTools/${part}" EXCLUDE_FROM_ALL)
 endforeach()
endif()
add_library(forge_gltf_native STATIC src/gltf_native.cpp)
target_include_directories(forge_gltf_native PRIVATE
 "${diligent_SOURCE_DIR}/DiligentTools/ThirdParty/tinygltf")
target_link_libraries(forge_gltf_native PUBLIC forge_assets PRIVATE Diligent-AssetLoader Diligent-GraphicsAccessories Diligent-BuildSettings)
if(WIN32)
 target_compile_definitions(forge_gltf_native PRIVATE NOMINMAX)
endif()
if(BUILD_TESTING)
 add_executable(forge_gltf_native_tests tests/gltf_native_tests.cpp)
 target_include_directories(forge_gltf_native_tests PRIVATE src
  "${diligent_SOURCE_DIR}/DiligentTools/ThirdParty/tinygltf")
 target_link_libraries(forge_gltf_native_tests PRIVATE forge_gltf_native)
 add_test(NAME gltf_native_capture COMMAND forge_gltf_native_tests "${CMAKE_BINARY_DIR}/gltf-native-tests")
 set_tests_properties(gltf_native_capture PROPERTIES TIMEOUT 45)
endif()
