# Reuse the common isolated worker/publication boundary. Only the worker and
# legacy runtime decode path link miniaudio; authoring validates cooked PCM.
add_library(forge_audio_pipeline STATIC src/audio_importer.cpp)
target_link_libraries(forge_audio_pipeline PUBLIC forge_assets forge_audio_data PRIVATE forge_import_process forge_asset_bytes)
set(_forge_audio_recipe_inputs "${CMAKE_CXX_COMPILER_ID};${CMAKE_CXX_COMPILER_VERSION};${CMAKE_CXX_FLAGS};${CMAKE_CXX_FLAGS_RELEASE};${CMAKE_MSVC_RUNTIME_LIBRARY};${FORGE_ENABLE_SANITIZERS}")
foreach(source src/audio_asset.hpp src/audio_asset.cpp src/audio_decode.cpp src/audio_bundle.hpp src/audio_bundle.cpp src/audio_importer.hpp src/audio_importer.cpp src/audio_worker.cpp src/import_process.cpp src/import_process.hpp src/asset_worker.cpp src/asset_worker.hpp cmake/dependencies.cmake cmake/audio_assets.cmake)
 set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${source}")
 file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/${source}" digest)
 string(APPEND _forge_audio_recipe_inputs ";${source}:${digest}")
endforeach()
string(SHA256 _forge_audio_recipe_fingerprint "${_forge_audio_recipe_inputs}")
target_compile_definitions(forge_audio_pipeline PRIVATE FORGE_AUDIO_RECIPE_FINGERPRINT="${_forge_audio_recipe_fingerprint}" FORGE_AUDIO_RECIPE_CONFIGURATION="$<CONFIG>")
add_library(forge_audio_authoring STATIC src/audio_authoring.cpp)
target_link_libraries(forge_audio_authoring PUBLIC forge_authoring forge_audio_pipeline)
if(BUILD_TESTING)
 add_executable(forge_audio_asset_tests tests/audio_asset_tests.cpp src/audio_worker.cpp)
 target_include_directories(forge_audio_asset_tests PRIVATE src)
 target_link_libraries(forge_audio_asset_tests PRIVATE forge_audio_authoring forge_audio_decode forge_simulation forge_asset_files)
 add_test(NAME audio_recipe COMMAND forge_audio_asset_tests --direct unused "${CMAKE_BINARY_DIR}/audio-recipe-tests")
 set_tests_properties(audio_recipe PROPERTIES TIMEOUT 60)
 if(NOT FORGE_ENABLE_SANITIZERS)
  add_dependencies(forge_audio_asset_tests forge_asset_build_worker)
  add_test(NAME audio_pipeline COMMAND forge_audio_asset_tests --worker $<TARGET_FILE:forge_asset_build_worker> "${CMAKE_BINARY_DIR}/audio-pipeline-tests")
  set_tests_properties(audio_pipeline PROPERTIES TIMEOUT 90)
 endif()
endif()
