if(NOT FORGE_BUILD_ASSET_TOOLS)
 message(FATAL_ERROR "The editor requires FORGE_BUILD_ASSET_TOOLS for its import workflows")
endif()
include(cmake/sdl.cmake)
FetchContent_Declare(imgui_source GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG b48d1afbe8ee8b238e2961dc363a949dd7304e23) # v1.92.9b-docking
FetchContent_MakeAvailable(imgui_source)
add_library(imgui STATIC ${imgui_source_SOURCE_DIR}/imgui.cpp ${imgui_source_SOURCE_DIR}/imgui_draw.cpp ${imgui_source_SOURCE_DIR}/imgui_tables.cpp ${imgui_source_SOURCE_DIR}/imgui_widgets.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_win32.cpp)
target_include_directories(imgui PUBLIC ${imgui_source_SOURCE_DIR})
target_link_libraries(imgui PRIVATE SDL3::SDL3)
set(DILIGENT_DEAR_IMGUI_PATH "${imgui_source_SOURCE_DIR}" CACHE PATH "" FORCE)
set(DILIGENT_BUILD_TOOLS ON CACHE BOOL "Editor tools include ImGui and asset loading" FORCE)
set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
set(DILIGENT_NO_DIRECT3D12 OFF CACHE BOOL "Editor renderer" FORCE)
set(DILIGENT_NO_HLSL OFF CACHE BOOL "Editor shader compilation" FORCE)
set(DILIGENT_NO_GLSLANG OFF CACHE BOOL "Retain editor shader compiler profile" FORCE)
set(DILIGENT_NO_ARCHIVER OFF CACHE BOOL "Retain editor Core profile" FORCE)
set(DILIGENT_NO_SUPER_RESOLUTION OFF CACHE BOOL "Retain editor Core profile" FORCE)
set(DILIGENT_ENABLE_DRACO OFF CACHE BOOL "Enable only with codec admission integration" FORCE)
set(DILIGENT_USE_RAPIDJSON OFF CACHE BOOL "Retain selected native loader JSON implementation" FORCE)
set(DILIGENT_NO_DIRECT3D11 ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_OPENGL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_VULKAN ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_METAL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_WEBGPU ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_RENDER_STATE_PACKAGER ON CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
include(cmake/diligent_source.cmake)
FetchContent_MakeAvailable(diligent)
include(cmake/pbr.cmake)
add_library(forge_shader_diligent src/shader_diligent.cpp)
target_include_directories(forge_shader_diligent PUBLIC "${diligent_SOURCE_DIR}/DiligentCore" PRIVATE src)
target_compile_definitions(forge_shader_diligent PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_shader_diligent PUBLIC forge_shader PRIVATE Diligent-GraphicsTools Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings d3dcompiler)
add_executable(forge_shader_build_worker src/shader_worker_main.cpp)
set_target_properties(forge_shader_build_worker PROPERTIES OUTPUT_NAME forge_shader_build)
target_compile_definitions(forge_shader_build_worker PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_shader_build_worker PRIVATE forge_shader_pipeline forge_import_process forge_shader_diligent Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings d3d12 dxgi)
copy_required_dlls(forge_shader_build_worker)
add_executable(forge_editor src/editor/main.cpp src/editor/viewport.cpp)
add_dependencies(forge_editor forge_shader_build_worker)
target_include_directories(forge_editor PRIVATE src/editor "${diligent_SOURCE_DIR}/DiligentCore")
target_compile_definitions(forge_editor PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_editor PRIVATE forge_presentation_diligent forge_navigation_build forge_navigation_admission forge_animation_conversion forge_authoring SDL3::SDL3 imgui Diligent-Imgui Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings)
copy_required_dlls(forge_editor)
add_custom_command(TARGET forge_editor POST_BUILD
 COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:forge_editor>/sdk/include/forge" "$<TARGET_FILE_DIR:forge_editor>/sdk/samples/native"
 COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/include/forge/module_api.h" "$<TARGET_FILE_DIR:forge_editor>/sdk/include/forge/"
 COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/samples/native/movement.c" "${PROJECT_SOURCE_DIR}/samples/native/CMakeLists.txt" "$<TARGET_FILE_DIR:forge_editor>/sdk/samples/native/")

if(BUILD_TESTING)
 add_executable(forge_shader_worker_tests tests/shader_worker_tests.cpp)
 target_include_directories(forge_shader_worker_tests PRIVATE src)
 target_link_libraries(forge_shader_worker_tests PRIVATE forge_shader_authoring forge_shader_diligent forge_shader_resources forge_asset_bytes)
 add_dependencies(forge_shader_worker_tests forge_shader_build_worker)
 copy_required_dlls(forge_shader_worker_tests)
 add_test(NAME shader_worker COMMAND forge_shader_worker_tests $<TARGET_FILE:forge_shader_build_worker> "${CMAKE_BINARY_DIR}/shader-worker-tests")
 set_tests_properties(shader_worker PROPERTIES TIMEOUT 180)
 add_executable(forge_viewport_tests tests/viewport_render_tests.cpp src/editor/viewport.cpp)
 target_include_directories(forge_viewport_tests PRIVATE src src/editor "${diligent_SOURCE_DIR}/DiligentCore")
 target_compile_definitions(forge_viewport_tests PRIVATE UNICODE _UNICODE NOMINMAX)
 target_link_libraries(forge_viewport_tests PRIVATE forge_authoring imgui Diligent-Imgui Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings d3d12 dxgi)
 copy_required_dlls(forge_viewport_tests)
 target_link_libraries(forge_viewport_tests PRIVATE forge_shader_diligent forge_presentation_diligent)
 add_test(NAME editor_viewport_render COMMAND forge_viewport_tests "${CMAKE_BINARY_DIR}/grid-test-images")
 set_tests_properties(editor_viewport_render PROPERTIES TIMEOUT 60)
 add_executable(forge_editor_native_tests tests/editor_native_tests.cpp)
 target_include_directories(forge_editor_native_tests PRIVATE src/editor)
 target_link_libraries(forge_editor_native_tests PRIVATE forge_authoring SDL3::SDL3)
 add_test(NAME editor_native_iteration COMMAND forge_editor_native_tests "${PROJECT_SOURCE_DIR}" $<TARGET_FILE:forge_runtime> "${CMAKE_COMMAND}" "${CMAKE_MAKE_PROGRAM}")
 set_tests_properties(editor_native_iteration PROPERTIES TIMEOUT 240)
 add_executable(forge_fault_runtime tests/fault_runtime.cpp)
 target_link_libraries(forge_fault_runtime PRIVATE nlohmann_json::nlohmann_json)
 add_executable(forge_editor_tests tests/editor_tests.cpp)
 target_include_directories(forge_editor_tests PRIVATE src/editor)
 target_link_libraries(forge_editor_tests PRIVATE forge_navigation_build forge_navigation_admission forge_animation_conversion forge_authoring SDL3::SDL3 imgui)
 add_test(NAME editor_process_and_scale COMMAND forge_editor_tests $<TARGET_FILE:forge_runtime> $<TARGET_FILE:forge_fault_runtime>)
 set_tests_properties(editor_process_and_scale PROPERTIES TIMEOUT 45)
endif()

if(NOT FORGE_BUILD_UI_PRESENTER)
 message(FATAL_ERROR "The editor requires FORGE_BUILD_UI_PRESENTER")
endif()
add_library(forge_ui_diligent src/ui_diligent.cpp)
target_include_directories(forge_ui_diligent PRIVATE "${diligent_SOURCE_DIR}/DiligentCore")
target_link_libraries(forge_ui_diligent PUBLIC forge_ui_presenter PRIVATE RmlUi::Core Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings)
target_link_libraries(forge_editor PRIVATE forge_ui_diligent)
add_custom_command(TARGET forge_editor POST_BUILD
 COMMAND ${CMAKE_COMMAND} -E copy_directory "${PROJECT_SOURCE_DIR}/resources/ui" "$<TARGET_FILE_DIR:forge_editor>/resources/ui")

# Reuse upstream SDL3 key/modifier and IME translation only; FORGE owns routing.
target_sources(forge_editor PRIVATE "${rmlui_SOURCE_DIR}/Backends/RmlUi_Platform_SDL.cpp")
target_include_directories(forge_editor PRIVATE "${rmlui_SOURCE_DIR}/Backends")
target_compile_definitions(forge_editor PRIVATE RMLUI_SDL_VERSION_MAJOR=3)
target_link_libraries(forge_editor PRIVATE RmlUi::Core)

if(BUILD_TESTING)
 add_executable(forge_ui_render_tests tests/ui_render_tests.cpp)
 target_include_directories(forge_ui_render_tests PRIVATE "${diligent_SOURCE_DIR}/DiligentCore")
 target_compile_definitions(forge_ui_render_tests PRIVATE UNICODE _UNICODE NOMINMAX)
 target_link_libraries(forge_ui_render_tests PRIVATE forge_ui_diligent RmlUi::Core Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings d3d12 dxgi)
 copy_required_dlls(forge_ui_render_tests)
 add_test(NAME runtime_ui_render COMMAND forge_ui_render_tests "${CMAKE_BINARY_DIR}/ui-test-images" "${PROJECT_SOURCE_DIR}/resources/ui/LatoLatin-Regular.ttf")
endif()
if(BUILD_TESTING)
 add_executable(forge_ui_input_tests tests/ui_input_tests.cpp "${rmlui_SOURCE_DIR}/Backends/RmlUi_Platform_SDL.cpp")
 target_include_directories(forge_ui_input_tests PRIVATE src/editor "${rmlui_SOURCE_DIR}/Backends")
 target_compile_definitions(forge_ui_input_tests PRIVATE RMLUI_SDL_VERSION_MAJOR=3)
 target_link_libraries(forge_ui_input_tests PRIVATE forge_ui_presenter forge_authoring RmlUi::Core SDL3::SDL3 imgui)
 add_test(NAME runtime_ui_input COMMAND forge_ui_input_tests $<TARGET_FILE:forge_runtime> "${PROJECT_SOURCE_DIR}/resources/ui/LatoLatin-Regular.ttf" "${CMAKE_BINARY_DIR}/ui-input-data")
endif()

# Render the actual editor UI on WARP in a disposable project/preferences directory.
if(BUILD_TESTING)
 add_executable(forge_editor_fixture src/editor/main.cpp src/editor/viewport.cpp)
 get_target_property(editor_links forge_editor LINK_LIBRARIES)
 get_target_property(editor_includes forge_editor INCLUDE_DIRECTORIES)
 get_target_property(editor_definitions forge_editor COMPILE_DEFINITIONS)
 target_include_directories(forge_editor_fixture PRIVATE tests ${editor_includes})
 target_compile_definitions(forge_editor_fixture PRIVATE ${editor_definitions} FORGE_UI_FIXTURE=1)
 target_link_libraries(forge_editor_fixture PRIVATE ${editor_links} d3d12 dxgi)
 target_sources(forge_editor_fixture PRIVATE "${rmlui_SOURCE_DIR}/Backends/RmlUi_Platform_SDL.cpp")
 add_dependencies(forge_editor_fixture forge_editor forge_runtime)
 copy_required_dlls(forge_editor_fixture)
 add_test(NAME editor_redesign_render COMMAND forge_editor_fixture "${CMAKE_BINARY_DIR}/grid-test-images/editor")
 set_tests_properties(editor_redesign_render PROPERTIES TIMEOUT 120)
endif()
