FetchContent_Declare(sdl GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG 96292a5b464258a2b926e0a3d72f8b98c2a81aa6)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(sdl)
FetchContent_Declare(imgui_source GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG 1f7f1f54af38b0350d8c0008b096a9af6de299c7)
FetchContent_MakeAvailable(imgui_source)
add_library(imgui STATIC ${imgui_source_SOURCE_DIR}/imgui.cpp ${imgui_source_SOURCE_DIR}/imgui_draw.cpp ${imgui_source_SOURCE_DIR}/imgui_tables.cpp ${imgui_source_SOURCE_DIR}/imgui_widgets.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_win32.cpp)
target_include_directories(imgui PUBLIC ${imgui_source_SOURCE_DIR})
target_link_libraries(imgui PRIVATE SDL3::SDL3)
set(DILIGENT_DEAR_IMGUI_PATH "${imgui_source_SOURCE_DIR}" CACHE PATH "" FORCE)
set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
set(DILIGENT_NO_DIRECT3D11 ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_OPENGL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_VULKAN ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_METAL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_WEBGPU ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_RENDER_STATE_PACKAGER ON CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(diligent GIT_REPOSITORY https://github.com/DiligentGraphics/DiligentEngine.git GIT_TAG a279e5fa8593cbc758ec46ea1eba0b435cbc2f06)
FetchContent_MakeAvailable(diligent)
add_executable(forge_editor src/editor/main.cpp src/editor/viewport.cpp)
target_include_directories(forge_editor PRIVATE src/editor "${diligent_SOURCE_DIR}/DiligentCore")
target_compile_definitions(forge_editor PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_editor PRIVATE forge_core SDL3::SDL3 imgui Diligent-Imgui Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings)
copy_required_dlls(forge_editor)

if(BUILD_TESTING)
 add_executable(forge_fault_runtime tests/fault_runtime.cpp)
 target_link_libraries(forge_fault_runtime PRIVATE nlohmann_json::nlohmann_json)
 add_executable(forge_editor_tests tests/editor_tests.cpp)
 target_include_directories(forge_editor_tests PRIVATE src/editor)
 target_link_libraries(forge_editor_tests PRIVATE forge_core SDL3::SDL3 imgui)
 add_test(NAME editor_process_and_scale COMMAND forge_editor_tests $<TARGET_FILE:forge_runtime> $<TARGET_FILE:forge_fault_runtime>)
 set_tests_properties(editor_process_and_scale PROPERTIES TIMEOUT 20)
endif()
