FetchContent_Declare(sdl GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG fa2c02bb6e21974a89ea9824bc53c9932abe5f9c) # release-3.4.16
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(sdl)
FetchContent_Declare(imgui_source GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG b48d1afbe8ee8b238e2961dc363a949dd7304e23) # v1.92.9b-docking
FetchContent_MakeAvailable(imgui_source)
add_library(imgui STATIC ${imgui_source_SOURCE_DIR}/imgui.cpp ${imgui_source_SOURCE_DIR}/imgui_draw.cpp ${imgui_source_SOURCE_DIR}/imgui_tables.cpp ${imgui_source_SOURCE_DIR}/imgui_widgets.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp ${imgui_source_SOURCE_DIR}/backends/imgui_impl_win32.cpp)
target_include_directories(imgui PUBLIC ${imgui_source_SOURCE_DIR})
target_link_libraries(imgui PRIVATE SDL3::SDL3)
set(DILIGENT_DEAR_IMGUI_PATH "${imgui_source_SOURCE_DIR}" CACHE PATH "" FORCE)
set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
set(DILIGENT_NO_DIRECT3D11 ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_OPENGL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_VULKAN ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_METAL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_WEBGPU ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_RENDER_STATE_PACKAGER ON CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(diligent GIT_REPOSITORY https://github.com/DiligentGraphics/DiligentEngine.git GIT_TAG a279e5fa8593cbc758ec46ea1eba0b435cbc2f06)
FetchContent_MakeAvailable(diligent)
add_executable(forge_editor src/editor/main.cpp src/editor/viewport.cpp)
target_include_directories(forge_editor PRIVATE src/editor "${diligent_SOURCE_DIR}/DiligentCore")
target_compile_definitions(forge_editor PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_editor PRIVATE forge_authoring SDL3::SDL3 imgui Diligent-Imgui Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings)
copy_required_dlls(forge_editor)
add_custom_command(TARGET forge_editor POST_BUILD
 COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:forge_editor>/sdk/include/forge" "$<TARGET_FILE_DIR:forge_editor>/sdk/samples/native"
 COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/include/forge/module_api.h" "$<TARGET_FILE_DIR:forge_editor>/sdk/include/forge/"
 COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PROJECT_SOURCE_DIR}/samples/native/movement.c" "${PROJECT_SOURCE_DIR}/samples/native/CMakeLists.txt" "$<TARGET_FILE_DIR:forge_editor>/sdk/samples/native/")

if(BUILD_TESTING)
 add_executable(forge_viewport_tests tests/viewport_render_tests.cpp src/editor/viewport.cpp)
 target_include_directories(forge_viewport_tests PRIVATE src/editor "${diligent_SOURCE_DIR}/DiligentCore")
 target_compile_definitions(forge_viewport_tests PRIVATE UNICODE _UNICODE NOMINMAX)
 target_link_libraries(forge_viewport_tests PRIVATE forge_core imgui Diligent-Imgui Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings d3d12 dxgi)
 copy_required_dlls(forge_viewport_tests)
 add_test(NAME editor_viewport_render COMMAND forge_viewport_tests "${CMAKE_BINARY_DIR}/grid-test-images")
 set_tests_properties(editor_viewport_render PROPERTIES TIMEOUT 60)
 add_executable(forge_editor_native_tests tests/editor_native_tests.cpp)
 target_include_directories(forge_editor_native_tests PRIVATE src/editor)
 target_link_libraries(forge_editor_native_tests PRIVATE forge_core SDL3::SDL3)
 add_test(NAME editor_native_iteration COMMAND forge_editor_native_tests "${PROJECT_SOURCE_DIR}" $<TARGET_FILE:forge_runtime> "${CMAKE_COMMAND}" "${CMAKE_MAKE_PROGRAM}")
 set_tests_properties(editor_native_iteration PROPERTIES TIMEOUT 240)
 add_executable(forge_fault_runtime tests/fault_runtime.cpp)
 target_link_libraries(forge_fault_runtime PRIVATE nlohmann_json::nlohmann_json)
 add_executable(forge_editor_tests tests/editor_tests.cpp)
 target_include_directories(forge_editor_tests PRIVATE src/editor)
 target_link_libraries(forge_editor_tests PRIVATE forge_authoring SDL3::SDL3 imgui)
 add_test(NAME editor_process_and_scale COMMAND forge_editor_tests $<TARGET_FILE:forge_runtime> $<TARGET_FILE:forge_fault_runtime>)
 set_tests_properties(editor_process_and_scale PROPERTIES TIMEOUT 20)
endif()
