if(FORGE_ENABLE_NATIVE_SDK)
 install(FILES "${recast_SOURCE_DIR}/License.txt" DESTINATION licenses COMPONENT NativeSdk RENAME recast.txt)
 install(DIRECTORY "${json_SOURCE_DIR}/include/nlohmann" DESTINATION sdk/include COMPONENT NativeSdk)
 install(FILES "${ozz_SOURCE_DIR}/LICENSE.md" DESTINATION licenses COMPONENT NativeSdk RENAME ozz.txt)
 install(FILES "${miniaudio_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME miniaudio.txt)
 set(FORGE_SDK_CONFIG_FLAGS "${CMAKE_CXX_FLAGS_${_forge_config}}")
 configure_file(cmake/ForgeNativeSdkConfig.cmake.in ForgeNativeSdkConfig.cmake @ONLY)
 install(TARGETS forge_runtime RUNTIME DESTINATION bin COMPONENT NativeSdk)
 install(TARGETS flecs RUNTIME DESTINATION bin COMPONENT NativeSdk LIBRARY DESTINATION bin COMPONENT NativeSdk ARCHIVE DESTINATION sdk/lib COMPONENT NativeSdk)
 install(DIRECTORY "${flecs_SOURCE_DIR}/include/" DESTINATION sdk/include COMPONENT NativeSdk FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp" PATTERN "*.inl")
 foreach(header IN LISTS FORGE_SDK_HEADERS)
  install(FILES "include/forge/${header}" DESTINATION sdk/include/forge COMPONENT NativeSdk)
 endforeach()
 install(FILES "${CMAKE_BINARY_DIR}/generated/forge/native_sdk_identity.h" DESTINATION sdk/include/forge COMPONENT NativeSdk)
 install(TARGETS forge_identity ARCHIVE DESTINATION sdk/lib COMPONENT NativeSdk)
 install(FILES docs/extension-guide.md docs/extension-contracts.md DESTINATION sdk/docs COMPONENT NativeSdk)
 install(FILES "${CMAKE_BINARY_DIR}/ForgeNativeSdkConfig.cmake" cmake/module_kit_install.cmake.in DESTINATION sdk COMPONENT NativeSdk)
 install(DIRECTORY samples/native_sdk/ DESTINATION sdk/sample COMPONENT NativeSdk)
 install(FILES "${CMAKE_BINARY_DIR}/build.json" DESTINATION . COMPONENT NativeSdk)
 install(FILES "${flecs_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME flecs.txt)
 install(FILES "${jolt_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME jolt.txt)
 install(FILES "${json_SOURCE_DIR}/LICENSE.MIT" DESTINATION licenses COMPONENT NativeSdk RENAME json.txt)
 if(MSVC AND NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION bin)
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_COMPONENT NativeSdk)
  include(InstallRequiredSystemLibraries)
 endif()
endif()
