if(FORGE_ENABLE_NATIVE_SDK)
 install(FILES "${recast_SOURCE_DIR}/License.txt" DESTINATION licenses COMPONENT NativeSdk RENAME recast.txt)
 install(DIRECTORY "${json_SOURCE_DIR}/include/nlohmann" DESTINATION sdk/include COMPONENT NativeSdk)
 install(FILES "${ozz_SOURCE_DIR}/LICENSE.md" DESTINATION licenses COMPONENT NativeSdk RENAME ozz.txt)
 install(FILES "${miniaudio_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME miniaudio.txt)
 configure_file(cmake/ForgeNativeSdkConfig.cmake.in ForgeNativeSdkConfig.cmake @ONLY)
 install(TARGETS forge_runtime RUNTIME DESTINATION bin COMPONENT NativeSdk)
 install(TARGETS flecs RUNTIME DESTINATION bin COMPONENT NativeSdk LIBRARY DESTINATION bin COMPONENT NativeSdk ARCHIVE DESTINATION sdk/lib COMPONENT NativeSdk)
 install(DIRECTORY "${flecs_SOURCE_DIR}/include/" DESTINATION sdk/include COMPONENT NativeSdk FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp" PATTERN "*.inl")
 install(FILES include/forge/ui_components.hpp include/forge/navigation_components.hpp include/forge/animation_components.hpp include/forge/audio_components.hpp include/forge/assets.hpp include/forge/identity.hpp include/forge/physics_components.hpp include/forge/native_sdk.h "${CMAKE_BINARY_DIR}/generated/forge/native_sdk_identity.h" DESTINATION sdk/include/forge COMPONENT NativeSdk)
 install(FILES "${CMAKE_BINARY_DIR}/ForgeNativeSdkConfig.cmake" DESTINATION sdk COMPONENT NativeSdk)
 install(DIRECTORY samples/native_sdk/ DESTINATION sdk/sample COMPONENT NativeSdk)
 install(FILES "${CMAKE_BINARY_DIR}/build.json" DESTINATION . COMPONENT NativeSdk)
 install(FILES "${flecs_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME flecs.txt)
 install(FILES "${jolt_SOURCE_DIR}/LICENSE" DESTINATION licenses COMPONENT NativeSdk RENAME jolt.txt)
 install(FILES "${json_SOURCE_DIR}/LICENSE.MIT" DESTINATION licenses COMPONENT NativeSdk RENAME json.txt)
 if(MSVC AND NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION bin)
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_COMPONENT NativeSdk)
  include(InstallRequiredSystemLibraries)
 endif()
endif()
