# Shared Flecs is an explicit profile; never link a private static copy into an SDK module.
set(FORGE_LINKAGE_PROFILE "static-abi1")
if(FORGE_ENABLE_NATIVE_SDK)
 set(FORGE_LINKAGE_PROFILE "shared-native-sdk")
 if(MSVC)
  set(_forge_crt MultiThreadedDLL)
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(_forge_crt MultiThreadedDebugDLL)
  endif()
  if(CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
   set(CMAKE_MSVC_RUNTIME_LIBRARY "${_forge_crt}")
  endif()
  if(NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL _forge_crt)
   message(FATAL_ERROR "Native SDK requires matching /MD Release or /MDd Debug CRT")
  endif()
 endif()
endif()
if(FORGE_ENABLE_NATIVE_SDK AND NOT CMAKE_BUILD_TYPE MATCHES "^(Release|Debug|RelWithDebInfo|MinSizeRel)$")
 message(FATAL_ERROR "Select an explicit build configuration")
endif()
string(TOUPPER "${CMAKE_BUILD_TYPE}" _forge_config)
# One explicit installed value boundary drives installation and compatibility hashing.
set(FORGE_SDK_HEADERS native_sdk.h sdk_client.hpp identity.hpp asset_ref.hpp physics_components.hpp audio_components.hpp animation_components.hpp navigation_components.hpp ui_components.hpp render_components.hpp model_asset.hpp engine_assets.hpp primitive_catalog.hpp)
set(FORGE_SDK_CONTRACT_HASHES "")
foreach(header IN LISTS FORGE_SDK_HEADERS)
 set(path "${PROJECT_SOURCE_DIR}/include/forge/${header}")
 set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
 file(SHA256 "${path}" hash)
 string(APPEND FORGE_SDK_CONTRACT_HASHES "${header}:${hash};")
endforeach()
# Exact bridge and value-support semantics are part of this private SDK contract.
foreach(source src/native_sdk.cpp src/identity.cpp src/authored_schema.cpp src/authored_schema.hpp src/reflected_value.cpp src/reflected_native.cpp src/reconstructed_meta.cpp src/reflected_extensions.cpp)
 set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/${source}")
 file(SHA256 "${PROJECT_SOURCE_DIR}/${source}" hash)
 string(APPEND FORGE_SDK_CONTRACT_HASHES "${source}:${hash};")
endforeach()
string(SHA256 FORGE_NATIVE_SDK_FINGERPRINT "exact2;flecs-script-math=1;visual-scale=signed-zero-v1;${FORGE_SDK_CONTRACT_HASHES};flecs-fb55f3c25660425cfe1bc4cf5e6bff8b3f18a9b8;${FORGE_LINKAGE_PROFILE};${CMAKE_SYSTEM_NAME};${CMAKE_SYSTEM_PROCESSOR};${CMAKE_SIZEOF_VOID_P};${CMAKE_CXX_COMPILER_ID};${CMAKE_CXX_COMPILER_VERSION};${MSVC_TOOLSET_VERSION};${CMAKE_BUILD_TYPE};${CMAKE_MSVC_RUNTIME_LIBRARY};${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_C_FLAGS_${_forge_config}};${CMAKE_CXX_FLAGS_${_forge_config}};${FORGE_ENABLE_SANITIZERS}")
configure_file(cmake/native_sdk_identity.h.in generated/forge/native_sdk_identity.h @ONLY)
