# Shared Flecs is an explicit profile; never link a private static copy into an SDK module.
set(FORGE_LINKAGE_PROFILE "static-abi1")
if(FORGE_ENABLE_NATIVE_SDK)
 set(FORGE_LINKAGE_PROFILE "shared-native-sdk")
 if(MSVC)
  set(_forge_crt MultiThreadedDLL)
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
   set(_forge_crt MultiThreadedDebugDLL)
  endif()
  if(CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
   set(CMAKE_MSVC_RUNTIME_LIBRARY "${_forge_crt}")
  endif()
  if(NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL _forge_crt)
   message(FATAL_ERROR "Native SDK requires matching /MD Release or /MDd Debug CRT")
  endif()
 endif()
endif()
if(FORGE_ENABLE_NATIVE_SDK AND NOT CMAKE_BUILD_TYPE MATCHES "^(Release|Debug|RelWithDebInfo|MinSizeRel)$")
 message(FATAL_ERROR "Select an explicit build configuration")
endif()
string(TOUPPER "${CMAKE_BUILD_TYPE}" _forge_config)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/include/forge/native_sdk.h")
file(SHA256 "${PROJECT_SOURCE_DIR}/include/forge/native_sdk.h" FORGE_NATIVE_ABI_HASH)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/include/forge/physics_components.hpp")
file(SHA256 "${PROJECT_SOURCE_DIR}/include/forge/physics_components.hpp" FORGE_PHYSICS_ABI_HASH)
string(SHA256 FORGE_NATIVE_SDK_FINGERPRINT "internal1;${FORGE_NATIVE_ABI_HASH};${FORGE_PHYSICS_ABI_HASH};flecs-fb55f3c25660425cfe1bc4cf5e6bff8b3f18a9b8;${FORGE_LINKAGE_PROFILE};${CMAKE_SYSTEM_NAME};${CMAKE_SYSTEM_PROCESSOR};${CMAKE_SIZEOF_VOID_P};${CMAKE_CXX_COMPILER_ID};${CMAKE_CXX_COMPILER_VERSION};${MSVC_TOOLSET_VERSION};${CMAKE_BUILD_TYPE};${CMAKE_MSVC_RUNTIME_LIBRARY};${CMAKE_C_FLAGS};${CMAKE_CXX_FLAGS};${CMAKE_C_FLAGS_${_forge_config}};${CMAKE_CXX_FLAGS_${_forge_config}};${FORGE_ENABLE_SANITIZERS}")
configure_file(cmake/native_sdk_identity.h.in generated/forge/native_sdk_identity.h @ONLY)
