include_guard(GLOBAL)
# Device/render composition shared by the editor and standalone game host.
set(DILIGENT_BUILD_TOOLS ${FORGE_BUILD_EDITOR} CACHE BOOL "Editor-only upstream tools" FORCE)
set(DILIGENT_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DILIGENT_BUILD_FX OFF CACHE BOOL "" FORCE)
set(DILIGENT_NO_DIRECT3D12 OFF CACHE BOOL "Editor renderer" FORCE)
set(DILIGENT_NO_HLSL OFF CACHE BOOL "Editor shader compilation" FORCE)
set(DILIGENT_NO_GLSLANG OFF CACHE BOOL "Retain editor shader compiler profile" FORCE)
set(DILIGENT_NO_ARCHIVER OFF CACHE BOOL "Retain editor Core profile" FORCE)
set(DILIGENT_NO_SUPER_RESOLUTION OFF CACHE BOOL "Retain editor Core profile" FORCE)
set(DILIGENT_ENABLE_DRACO OFF CACHE BOOL "Enable only with codec admission integration" FORCE)
set(DILIGENT_USE_RAPIDJSON OFF CACHE BOOL "Retain selected native loader JSON implementation" FORCE)
set(DILIGENT_NO_DIRECT3D11 ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_OPENGL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_VULKAN ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_METAL ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_WEBGPU ON CACHE BOOL "" FORCE)
set(DILIGENT_NO_RENDER_STATE_PACKAGER ON CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_CORE OFF CACHE BOOL "" FORCE)
set(DILIGENT_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
include(cmake/diligent_source.cmake)
FetchContent_MakeAvailable(diligent)
include(cmake/pbr.cmake)
add_library(forge_shader_diligent src/shader_diligent.cpp)
target_include_directories(forge_shader_diligent PUBLIC "${diligent_SOURCE_DIR}/DiligentCore" PRIVATE src)
target_compile_definitions(forge_shader_diligent PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(forge_shader_diligent PUBLIC forge_shader Diligent-BuildSettings PRIVATE Diligent-GraphicsTools Diligent-GraphicsEngineD3D12-shared d3dcompiler)

if(NOT FORGE_BUILD_UI_PRESENTER)
 message(FATAL_ERROR "Graphical hosts require FORGE_BUILD_UI_PRESENTER")
endif()
add_library(forge_ui_diligent src/ui_diligent.cpp)
target_include_directories(forge_ui_diligent PRIVATE "${diligent_SOURCE_DIR}/DiligentCore")
target_link_libraries(forge_ui_diligent PUBLIC forge_ui_presenter PRIVATE RmlUi::Core Diligent-GraphicsEngineD3D12-shared Diligent-BuildSettings)
